title: Stewart Aimiebenomon
logo: Data_Image.jpeg
description: I am a Data Analyst with two years experience working with statistical tools such SQL for Data Interogation and Manipulation, Advanced Microsoft Excel and Power BI for creating business intelligence Dashboard
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
